### ISSUE TITLE
Picture does not update any more

### ISSUE THREAD

**Issue by wbleek** [spectroman/mmm-moon-phases#3]
The moon picture stays the same for some days now. Is there a known issue? How can I clear the cache to force loading of a new picture?

**Comment by wbleek** [comment]
By rebooting I can make it look the current one. However, after a few days, it is stuck again.

**Comment by spectroman** [comment]
It took sometime but I could address the refreshing problem, which I also had.

I made a new effort to create a framework to download a cached image and load it locally. Because the name will be always different the update will always happen.

Further this week (29th July 17) the website I was using as a source got broken and the images are gone.. so I got temporarily a new source to make it work..

Right now the problem of refresh and the image source are both fixed on this new release.
