### ISSUE TITLE
MM2 does not display modules AFTER mmm-moon-phases

### ISSUE THREAD

**Issue by wbleek** [spectroman/mmm-moon-phases#4]
Hi,
I have installed your July Update to fix the reload problem. The moon displays but the all modules after that in the config file are not displayed. Can you reproduce the problem? What should I provide to you in order to support investigation?
Cheers
Wolf Bleek

**Comment by spectroman** [comment]
Hi!
Can you send me you conf file?

**Comment by wbleek** [comment]
Hey, great hearing from you!

Attached I have my config file.
The moon-module is commented out since this is my current state. If  I remove the comment the problem exists.
For security reasons I had to cut my apiKey and also cut my access URLs for the calendars.
Hopefully this does not hinder you.

I hope I don’t embarrass myself with any syntax error.

Cheers
Wgb

**Comment by spectroman** [comment]
Hi,

I could not see the attachment, it seems u replied via email...

U could paste on the body, or attach the file on the comment box from github?

l8r

**Comment by wbleek** [comment]
Sorry for the trouble.
I attached the file. Had to zip it.
[config.js.spectroman.zip](https://github.com/spectroman/mmm-moon-phases/files/1293186/config.js.spectroman.zip)

**Comment by spectroman** [comment]
Hi Wolf,

Had few busy days here... 

I had the opportunity to look into the cfg file u had attached.

I think there is a mistake there, about one of the properties you are trying to set, I am not aware that you can set "height" as a property, even if there is a property like it, declaring purely "100" seems dubious , is it 'px', '%' or what?

But I cannot really find any reference of such property, in my example you may find:
```{
                module: 'mmm-moon-phases',
                header: 'Current Moon Phase',   // optionally you can add a header to this block
                position: 'bottom_left',        // this can be any of the regions
                config: {
                }
        },
```

Which might be enough to set this into different positions of the screen, while tweaking the "position" property.

The location of the module in which the module will be loaded. Possible values are top_ bar, top_left, top_center, top_right, upper_third, middle_center, lower_third, bottom_left, bottom_center, bottom_right, bottom_bar, fullscreen_above, and fullscreen_below. This field is optional but most modules require this field to set. Check the documentation of the module for more information. Multiple modules with the same position will be ordered based on the order in the configuration file.

Let me know if you have any developments there.

**Comment by wbleek** [comment]
Hi spectroman,

thanks very much for investigating my problem. You are right, the height 100 is dubious. I used it to shrink the picture a little. It works but it is more accurate with "px" at the end.

However, this is not the problem. Without the parameter or with the correct parameters ist does not work.

I used your code snipped instead of mine and the only thing I got was the "header". 

I also found out that if I move the module configuration to the end of the config file I get all modules up to the moon.

**Comment by spectroman** [comment]
ok,

Lets get practical:

If you could use the configuration that fails for you and take a snip from the log file so we can see if there is an error there... 

I don't know if you are using PM2, if so, you may find the following files, for example:

`/home/pi/.pm2/logs/mm-out-0.log`
`/home/pi/.pm2/logs/mm-error-0.log`

Make sure to reset the files to get current errors on loading the modules.

Also, the module is a bit crude on the fact of path to create the cache file, so you can look into the js files and make sure the path for creating the cache files are correct.. if would be the module doesn't have rights to create the directory / file.

I will make an update that contemplated those options, as such, people could use different locations.

It is important to note that the location must be along with the module, because it should be visible via the HTTP server from node.js..

In my case the cache directory sits at:

`/home/pi/MagicMirror/modules/mmm-moon-phases/cache`

Where he must create a file with the timestamp of the download, such as:

`moon-1506589576091.gif`

If it is all correct, you should be able to see the image downloaded by the module like this:

`http://your-mm-ip:8080/modules/mmm-moon-phases/cache/moon-1506589576091.gif`

----

So let's see those logs, maybe we can figure that one out.

**Comment by wbleek** [comment]
Hi,
thanks a lot for coming back on this matter.

I did clear the log-directory and used
`PM2 restart 0`
to restart the magic mirror

Even though I stripped the config a little I still have no module display after the moon module.

I got this output

`> magicmirror@2.1.2 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.1.2
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: mmm-moon-phases
No helper found for module: MMM-forecast-io.
Initializing new module helper ...
Module helper loaded: MMM-DWD-WarnWeather
Initializing new module helper ...
Module helper loaded: newsfeed
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: mmm-moon-phases
Starting node helper: mmm-moon-phases
Connecting socket for: MMM-DWD-WarnWeather
MMM-DWD-WarnWeather helper started...
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...
Launching application.
Create new news fetcher for url: https://www.deutsche-apotheker-zeitung.de/xml/news.rss2 - Interval: 300000
Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
Create new news fetcher for url: http://www.spiegel.de/schlagzeilen/tops/index.rss - Interval: 300000
Create new news fetcher for url: http://www.apotheke-adhoc.de/feed/topnews/ - Interval: 300000
Create new news fetcher for url: https://www.abda.de/social-navigation/rss/pressemitteilungen/ - Interval: 300000
Create new news fetcher for url: http://www.apotheken-umschau.de/rss/topthemen.xml - Interval: 300000
Create new news fetcher for url: https://www.aerzteblatt.de/rss/news.asp - Interval: 300000
Downloading moon img with signal: BRING_MOON From URL: tycho.usno.navy.mil/gif/phase.gif
`

in the `mm-out-0.log` file. there were no bytes written to the `mm-error-0.log` file.

The cache directory exists and the gif file is available.

Is there any other log file I could consult?

**Comment by spectroman** [comment]
Wolf!

Today I had a bit more time to analyze your configuration file and do some tests with it.

There are a few modules which are not really working there for you, I didn't went down the hole to figure it out... because I saw that after some of the modules break, my module also was breaking due to a failed call of a function.

It is weird that it works if other modules don't have an error, he only breaks in a specific condition.

Well, I fixed my module now, removing the call on the wrong place and testing you configuration now it works!

Let me know if that also works for you.

Thank you for notifying the problem and all the patience.

**Comment by wbleek** [comment]
Hey Spectroman!

Thanks a lot for your support. It works! Now the moon display is up and running again on my mirrors.

I'll close this issue now since you made the changes available on HEAD already. 

If you could point to some problems the other modules have please do not hesitate.

Thanks again
Wolf
